language: java

sudo: false

cache:
  directories:
  - $HOME/.mx/cache

before_install:
- rvm install 2.1.0
- unset GEM_PATH GEM_HOME IRBRC

jdk: oraclejdk8

matrix:
  include:
  - env: JT='test cexts_and_openssl' COMMAND=tool/install-sulong.sh
  # Exlude the default job https://github.com/travis-ci/travis-ci/issues/4681
  exclude:
  - jdk: oraclejdk8

install:
- git clone https://github.com/graalvm/mx
- export PATH=$PWD/mx:$PATH
- echo MX_BINARY_SUITES=truffle >> mx.truffleruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.truffleruby/env
- if [ -z "$SKIP_BUILD" ]; then mx build; fi
- $COMMAND
script:
- tool/jt.rb $JT

services:
- redis-server

branches:
  only:
    - master
    - /^try/
