language: java
dist: trusty
sudo: false

cache:
  directories:
  - $HOME/.mx/cache

addons:
  apt:
    packages:
    - libc++1
    - libc++abi1
    - libc++-dev
    - libc++abi-dev
    - libxml2
    - libxml2-dev

before_install:
- rvm use 2.3.1
- unset GEM_PATH GEM_HOME IRBRC

jdk: oraclejdk8

matrix:
  include:
  - env: JT='test cexts_and_openssl' COMMAND=tool/install-sulong.sh SULONG_HOME=../sulong LIBXML_LIB=/usr/lib/x86_64-linux-gnu/libxml2.so.2
  # Exlude the default job https://github.com/travis-ci/travis-ci/issues/4681
  exclude:
  - jdk: oraclejdk8

install:
- git clone https://github.com/graalvm/mx
- export PATH=$PWD/mx:$PATH
- echo MX_BINARY_SUITES=truffle >> mx.truffleruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.truffleruby/env
- if [ -z "$SKIP_BUILD" ]; then mx build; fi
- $COMMAND
script:
- tool/jt.rb $JT

services:
- redis-server

branches:
  only:
    - master
    - /^try/
