language: java
dist: trusty
sudo: false

cache:
  directories:
  - $HOME/.mx/cache

addons:
  apt:
    packages:
    - libc++1
    - libc++abi1
    - libc++-dev
    - libc++abi-dev
    - libxml2
    - libxml2-dev

before_install:
- rvm use 2.3.1
- unset GEM_PATH GEM_HOME IRBRC

jdk: oraclejdk8

matrix:
  include:
  - env: JT='test specs :command_line'
  - env: JT='test specs :language :security'
  - env: JT='test specs :core'
  - env: JT='test specs :library'
  - env: JT='test specs :truffle'
  - env: JT='test integration'
  - env: JT='test gems' COMMAND=test/truffle/gems/install-gems.sh
  - env: JT='test tck'
  - env: JT='lint' SKIP_BUILD=true V=1
  - env: JT='test mri'
  - env: JT='test bundle'
  - env: JT='test ecosystem actionpack actionview' JAVA_OPTS="$JAVA_OPTS -Xmx512m" COMMAND=test/truffle/ecosystem-travis-install.sh
  - env: JT='test ecosystem activemodel activesupport' JAVA_OPTS="$JAVA_OPTS -Xmx512m" COMMAND=test/truffle/ecosystem-travis-install.sh
  - env: JT='test ecosystem algebrick railties rails-app launchers' HAS_REDIS=true JAVA_OPTS="$JAVA_OPTS -Xmx512m" COMMAND=test/truffle/ecosystem-travis-install.sh
  - env: JT='test cexts_and_openssl' COMMAND=tool/install-sulong.sh SULONG_HOME=../sulong LIBXML_LIB=/usr/lib/x86_64-linux-gnu/libxml2.so OPENSSL_LIB=/usr/lib/x86_64-linux-gnu/libssl.so
  # Exlude the default job https://github.com/travis-ci/travis-ci/issues/4681
  exclude:
  - jdk: oraclejdk8

install:
- git clone https://github.com/graalvm/mx
- export PATH=$PWD/mx:$PATH
- echo MX_BINARY_SUITES=truffle >> mx.truffleruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.truffleruby/env
- if [ -z "$SKIP_BUILD" ]; then mx build; fi
- $COMMAND
script:
- tool/jt.rb $JT

services:
- redis-server

branches:
  only:
    - master
    - /^try/
