language: java

sudo: false

cache:
  directories:
  - $HOME/.mx/cache

before_install:
- unset GEM_PATH GEM_HOME IRBRC
- rvm install 2.1.0

jdk: oraclejdk8

matrix:
  include:
  - env: JT='test specs :command_line'
  - env: JT='test specs :language'
  - env: JT='test specs :core'
  - env: JT='test specs :library'
  - env: JT='test specs :truffle'
  - env: JT='test integration'
  - env: JT='test gems' COMMAND=test/truffle/gems/install-gems.sh
  - env: JT='test tck'
  - env: JT='check_dsl_usage' SKIP_BUILD=true V=1
  - env: JT='test mri'
  - env: JT='test bundle'
  - env: JT='test ecosystem actionpack actionview' JAVA_OPTS="$JAVA_OPTS -Xmx512m" COMMAND=test/truffle/ecosystem-travis-install.sh
  - env: JT='test ecosystem activemodel activesupport' JAVA_OPTS="$JAVA_OPTS -Xmx512m" COMMAND=test/truffle/ecosystem-travis-install.sh
  - env: JT='test ecosystem algebrick railties rails-app' HAS_REDIS=true JAVA_OPTS="$JAVA_OPTS -Xmx512m" COMMAND=test/truffle/ecosystem-travis-install.sh
  # Exlude the default job https://github.com/travis-ci/travis-ci/issues/4681
  exclude:
  - jdk: oraclejdk8

install:
- git clone https://github.com/graalvm/mx
- export PATH=$PWD/mx:$PATH
- echo MX_BINARY_SUITES=truffle >> mx.jruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.jruby/env
- if [ -z "$SKIP_BUILD" ]; then mx build; fi
- $COMMAND
script:
- tool/jt.rb $JT

services:
- redis-server

branches:
  only:
    - truffle-head
    - /^try/
