language: java

sudo: false

cache:
  directories:
  - $HOME/.mx/cache

before_install:
- unset GEM_PATH GEM_HOME IRBRC

jdk: oraclejdk8

matrix:
  include:
  - env: JT='test specs :command_line'
  - env: JT='test specs :language :security'
  - env: JT='test specs :core'
  - env: JT='test specs :library'
  - env: JT='test specs :truffle'
  - env: JT='test integration'
  - env: JT='test gems'
  - env: JT='test tck'
  - env: JT='lint' COMMAND='rvm install 2.1.0' SKIP_BUILD=true V=1
  - env: JT='test mri'
  - env: JT='test bundle'
  - env: JT='test ecosystem actionpack actionview' JAVA_OPTS="$JAVA_OPTS -Xmx512m"
  - env: JT='test ecosystem activemodel activesupport' JAVA_OPTS="$JAVA_OPTS -Xmx512m"
  - env: JT='test ecosystem algebrick railties rails-app launchers' HAS_REDIS=true JAVA_OPTS="$JAVA_OPTS -Xmx512m"
  - env: JT='test cexts_and_openssl --skip-bundle' COMMAND=tool/install-sulong.sh SULONG_VERSION=3.2 SULONG_HOME=../sulong LIBXML_LIB=/usr/lib/x86_64-linux-gnu/libxml2.so OPENSSL_LIB=/usr/lib/x86_64-linux-gnu/libssl.so
  # Exlude the default job https://github.com/travis-ci/travis-ci/issues/4681
  exclude:
  - jdk: oraclejdk8

install:
- git clone https://github.com/graalvm/mx
- export PATH=$PWD/mx:$PATH
- echo MX_BINARY_SUITES=truffle >> mx.truffleruby/env
- echo JAVA_HOME=$JAVA_HOME >> mx.truffleruby/env
- if [ -z "$SKIP_BUILD" ]; then mx build; fi
- $COMMAND
script:
- tool/jt.rb $JT

services:
- redis-server

branches:
  only:
    - master
    - /^try/
